# -*- coding: utf-8 -*-
"""yolo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OYhTHA4pD6spkx29ikefGNLWwUAK7_7L
"""


from roboflow import Roboflow
import os
from dotenv import load_dotenv
from ultralytics import YOLO

# Load the environment variables from the .env file
load_dotenv()
api_key = os.environ.get('API_KEY')

rf = Roboflow(api_key=api_key)
project = rf.workspace("university-bswxt").project("crack-bphdr")
dataset = project.version(2).download("yolov8")

# Command to train the model

model = YOLO('../crack-2/yolov8n.pt')
model.train(dataset, epochs=10, batch_size=8)
# !yolo train data=/content/crack-2/data.yaml model=yolov8n.pt epochs=10 lr0=0.01